### ISSUE TITLE
Ondat failing to download

### ISSUE THREAD

**Issue by echi01** [aws-ia/terraform-aws-eks-blueprints#1524]
## Description

╷
│ Error: Failed to download module
│ 
│ Could not download module "ondat" (infra/modules/kubernetes-addons/main.tf:364) source code from "git::https://github.com/ondat/terraform-eksblueprints-ondat-addon?ref=0.1.2": error downloading
│ 'https://github.com/ondat/terraform-eksblueprints-ondat-addon?ref=0.1.2': /usr/bin/git exited with 128: Cloning into '.terraform/modules/kubernetes_addons.ondat'...
│ remote: Repository `ondat/terraform-eksblueprints-ondat-addon' is disabled.
│ remote: Please ask the owner to check their account.
│ fatal: unable to access 'https://github.com/ondat/terraform-eksblueprints-ondat-addon/': The requested URL returned error: 403

If your request is for a new feature, please use the `Feature request` template.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

**Comment by alebricio** [comment]
Having the same issue.

**Comment by bryantbiggs** [comment]
fixed in #1523 - you will need to update to at least v4.27.0 to mitigate this issue

**Comment by yuniorh** [comment]
we tried that - still failing...

2023-03-30T20:02:14.1073232Z [0m[1mUpgrading modules...[0m
2023-03-30T20:02:14.5701859Z Downloading app.terraform.io/carnival/cclcom-eks/aws 1.2.9 for eks...
2023-03-30T20:02:15.6472544Z - eks in .terraform/modules/eks
2023-03-30T20:02:15.6473226Z Downloading git::https://github.com/aws-ia/terraform-aws-eks-blueprints.git?ref=v4.27.0 for eks.eks_blueprints...
2023-03-30T20:02:17.9196486Z - eks.eks_blueprints in .terraform/modules/eks.eks_blueprints

[...]

2023-03-30T20:02:32.3505021Z [31m[31m╷[0m[0m
2023-03-30T20:02:32.3505362Z [31m│[0m [0m[1m[31mError: [0m[0m[1mFailed to download module[0m
2023-03-30T20:02:32.3511743Z [31m│[0m [0m
2023-03-30T20:02:32.3512130Z [31m│[0m [0m[0mCould not download module "ondat"
2023-03-30T20:02:32.3512581Z [31m│[0m [0m(.terraform/modules/eks.eks_blueprints_kubernetes_addons/modules/kubernetes-addons/main.tf:352)
2023-03-30T20:02:32.3512828Z [31m│[0m [0msource code from
2023-03-30T20:02:32.3513115Z [31m│[0m [0m"git::https://github.com/ondat/terraform-eksblueprints-ondat-addon?ref=0.1.2":
2023-03-30T20:02:32.3513331Z [31m│[0m [0merror downloading
2023-03-30T20:02:32.3513588Z [31m│[0m [0m'https://github.com/ondat/terraform-eksblueprints-ondat-addon?ref=0.1.2':
2023-03-30T20:02:32.3583562Z [31m│[0m [0m/usr/bin/git exited with 128: Cloning into
2023-03-30T20:02:32.3584059Z [31m│[0m [0m'.terraform/modules/eks.eks_blueprints_kubernetes_addons.ondat'...
2023-03-30T20:02:32.3584757Z [31m│[0m [0mfatal: could not read Username for 'https://github.com': terminal prompts
2023-03-30T20:02:32.3585093Z [31m│[0m [0mdisabled
2023-03-30T20:02:32.3585252Z [31m│[0m [0m.
2023-03-30T20:02:32.3585401Z [31m╵[0m[0m

**Comment by xpicio** [comment]
@bryantbiggs please can you backport the fix to the previous versions ? I'm on 4.15.0 with two projects and the upgrade to 4.27 break both projects :(

**Comment by bryantbiggs** [comment]
we do not have the means to backport fixes - its a single branch (trunk based) and all changes move forward off of `main`. If you need to patch temporarily, you can fork the project at the version you are currently on, remove any references to Ondat, and use that fork until you are ready and in a position to update
